config/routes.rb
ExampleRegistrations::Application.routes.draw do
  root to: 'welcome#show'

  get '/auth/passport/callback' => 'omniauth_sessions#create'

  scope '/register' do
    get '/' => 'registrations#new', as: 'register'
    post '/' => 'orders#create'

    scope '/:order_id' do
      get '/other' => 'secondary_registrations#new', as: 'secondary_registration'
      post '/other' => 'orders#update'
      get '/confirm' => 'orders#show'
      get '/pay' => 'payments#new'
      post '/pay' => 'payments#create'
      get '/thanks' => 'thanks#show'
    end
  end

  get '/teams/register' => 'join_team_orders#new'
end

app/models/order.rb
require 'token'

class Order < ActiveRecord::Base
  belongs_to :user

  has_many :line_items
  has_many :registrations, through: :line_items, source: :sourceable, source_type: 'Registration'
  has_many :transactions

  def add_biller biller
    self.user = biller
  end

  def add_registration registration
    self.line_items.build sourceable: registration,
                          quantity: 1
  end

  def add_transaction transaction
    self.transactions << transaction
  end

  def checkout
    generate_token
    self.update_attributes state: 'checked_out'
  end

  def confirm
    self.update_attributes state: 'confirmed'
  end

  def paid
    self.update_attributes state: 'paid'
  end

  def generate_token
    self.update_attributes token: Token.generate
  end

  def primary_registrant
    registrations.first
  end

  def secondary_registrants
    registrations.secondaries
  end

  def total
    line_items.inject(0) { |total, item| total + item.total }
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  helper_method :registration, :order

  def create
    order = Order.new
    order.add_registration registration
    order.checkout

    redirect_to confirm_path(order_id: order)
  end

  def update
    order.add_registration registration
    order.save

    redirect_to confirm_path(order_id: order)
  end

  private

  def registration
    @registration ||= Registration.new create_params
  end

  def create_params
    params.require(:registration).permit :first_name, :surname,
      :nickname, :gender, :birthday, :fundraiser, :charity_id, :target,
      :distance, :email, :team_name
  end

  def order
    @order ||= Order.find params[:order_id]
  end
end

app/views/orders/new.html.erb
<%= simple_form_for form, as: 'form', url: register_path do |form| %>
  <%= form.error_notification %>

  <fieldset>
    <legend>Personal Information</legend>
    <%= form.input :first_name %>
    <%= form.input :surname %>
    <%= form.input :nickname %>
    <%= form.input :gender, as: :radio_buttons, collection: form.object.gender_options %>
    <%= form.input :birthday, as: :date, end_year: Time.zone.now.year,
                                         start_year: 1900 %>
  </fieldset>

  <fieldset>
    <legend>Fundraising Information</legend>
    <%= form.input :fundraiser, as: :radio_buttons, collection: form.object.fundraiser_options %>
    <%= form.input :charity_id, collection: form.object.charity_options %>
  </fieldset>

  <fieldset>
    <legend>Entry Information</legend>
    <%= form.input :distance, as: :radio_buttons, collection: form.object.distance_options %>
  </fieldset>

  <div class="form-actions">
    <%= form.button :submit, 'Confirm' %>
  </div>
<% end %>

app/views/orders/show.html.erb
<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
    <% order.line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.description %> (including fundraising: <%= line_item.sourceable.fundraiser?? 'yes' : 'no' %>)</td>
        <td><%= line_item.quantity %></td>
        <td><%= number_to_currency line_item.price %></td>
        <td><%= number_to_currency line_item.total %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td></td>
      <td colspan="2">Grand Total</td>
      <td><%= number_to_currency order.total %></td>
    </tr>
  </tfoot>
</table>

<%= link_to 'Add Another Registration', secondary_registration_path(order_id: order), class: 'button' %> |
<%= link_to 'Pay', pay_path(order_id: order), class: 'button' %>